// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARIFuWc67wCnFLeazTLOmc--CtUGP0UZA',
    appId: '1:329459505690:web:dd710138b44788ae900fa3',
    messagingSenderId: '329459505690',
    projectId: 'banbanshop',
    authDomain: 'banbanshop.firebaseapp.com',
    storageBucket: 'banbanshop.firebasestorage.app',
    measurementId: 'G-8D0FER6XCT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPW7zj9TLXyCtiZGMPOxIeWnIeAL7njKY',
    appId: '1:329459505690:android:ef21c8fee92c5677900fa3',
    messagingSenderId: '329459505690',
    projectId: 'banbanshop',
    storageBucket: 'banbanshop.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3LMcgxcVVo36wavl6dNR3Ic04iM64mw0',
    appId: '1:329459505690:ios:616edb32c0f1080f900fa3',
    messagingSenderId: '329459505690',
    projectId: 'banbanshop',
    storageBucket: 'banbanshop.firebasestorage.app',
    iosBundleId: 'com.example.banbanshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3LMcgxcVVo36wavl6dNR3Ic04iM64mw0',
    appId: '1:329459505690:ios:616edb32c0f1080f900fa3',
    messagingSenderId: '329459505690',
    projectId: 'banbanshop',
    storageBucket: 'banbanshop.firebasestorage.app',
    iosBundleId: 'com.example.banbanshop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARIFuWc67wCnFLeazTLOmc--CtUGP0UZA',
    appId: '1:329459505690:web:1714843a529f46d8900fa3',
    messagingSenderId: '329459505690',
    projectId: 'banbanshop',
    authDomain: 'banbanshop.firebaseapp.com',
    storageBucket: 'banbanshop.firebasestorage.app',
    measurementId: 'G-DNEK70DK3M',
  );

}